name = "Minecolonies Survival"
author = "CaptainVianite"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffef04c584b5306faaa27e85434aa45263d496aa0da9f94e670f0941b8dd13fd"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
