name = "All the Mods 7"
author = "ATMTeam"
version = "0.4.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "095a05f2f2eca37444e710807c0c1199feb228033cd227deded4bfa2c44d5675"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
