name = "Village Survival"
author = "CaptainVianite"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaed8a7d4618c7e54f98ac3787fda0ab50631fdfe66538aa8ac2dc408a303399"

[versions]
forge = "41.0.63"
minecraft = "1.19"
