name = "All the Mods 7"
author = "ATMTeam"
version = "0.4.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78ce12361108279bc1ec2433e6fa23c0fee427a55880b1c19e75dbf5e0daa6d3"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
