name = "All the Mods 7"
author = "ATMTeam"
version = "0.4.22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bae11be159efa56c1292877deab5b5d7ac5d6c6686021a41f7e3f4c6c9d4e97c"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
