name = "Village Survival"
author = "CaptainVianite"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f74f77a40cb5abe6753867e843b088eca765fecc873bdb48635ae5f86fecea6a"

[versions]
forge = "41.0.63"
minecraft = "1.19"
