name = "All the Mods 7"
author = "ATMTeam"
version = "0.4.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c31e6dd289368fc80dafa3eaffbe45cf9cc05b4ba84cca85416f07a253f523e"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
