name = "Village Survival"
author = "CaptainVianite"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6d39422e269be2ab72b2b49586f106bc34678b2094e46c3f198a92d68270ab9"

[versions]
forge = "41.0.63"
minecraft = "1.19"
